In [3]:
# install sklearn and pandas
!pip install --user --upgrade pip
!pip install --user sklearn
!pip install --user pandas 
import pickle, sklearn
import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np 
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression, LogisticRegression


Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.


# Load Dataset

In [5]:
with open("marketing", "rb") as f:
    dataset=pickle.load(f)
Marketing=dataset["Dataset"]


In [7]:
Marketing_X=Marketing[["Income","Year_Birth","Response"]]
Marketing_y=1*(Marketing["Kidhome"]>0)


In [14]:
Model=LinearRegression()
Model.fit(Marketing_X, Marketing_y)
Model.intercept_, Model.coef_,Model.predict(Marketing_X)

(-14.71790036725483,
 array([-8.04681861e-06,  7.90521260e-03, -3.05475618e-02]),
 array([0.25422719, 0.35596329, 0.23958557, ..., 0.48381002, 0.18749352,
        0.27291024]))

In [15]:
Model=LogisticRegression()
Model.fit(Marketing_X, Marketing_y)
Model.intercept_, Model.coef_,Model.predict(Marketing_X)

(array([7.38849531e-07]),
 array([[-6.43165404e-05,  1.46764709e-03,  2.36515767e-08]]),
 array([0, 0, 0, ..., 0, 0, 0]))