In [1]:
import torch
import torch.nn as nn
import numpy

In [19]:
tensor_cpu_random = torch.randn(2, 3)
tensor_gpu_random = tensor_cpu_random.cuda()


In [22]:
print(tensor_cpu_random)
print(tensor_gpu_random)
print(tensor_gpu_random.cpu())

tensor([[ 0.6466,  0.0508,  0.5567],
        [-0.2839,  0.7487, -0.9985]])
tensor([[ 0.6466,  0.0508,  0.5567],
        [-0.2839,  0.7487, -0.9985]], device='cuda:0')
tensor([[ 0.6466,  0.0508,  0.5567],
        [-0.2839,  0.7487, -0.9985]])


In [7]:
np_data = numpy.random.randint(0, 10, (2, 3))
torch_data = torch.from_numpy(np_data)
tensor_to_numpy = torch_data.numpy()

In [8]:
print(np_data)
print(torch_data)
print(tensor_to_numpy)

[[8 1 1]
 [7 3 1]]
tensor([[8, 1, 1],
        [7, 3, 1]], dtype=torch.int32)
[[8 1 1]
 [7 3 1]]


In [11]:
data = [ -1, -2, 1 , 2]
tensor_data = torch.FloatTensor(data)
print(tensor_data)
print(numpy.mean(data))
print(torch.mean(tensor_data))

tensor([-1., -2.,  1.,  2.])


tensor(0.)

In [16]:
data = [[1,2],[3,4]]
data_numpy_array = numpy.array(data)
data_tensor = torch.FloatTensor(data)
print(numpy.matmul(data, data))
print(data_numpy_array.dot(data_numpy_array))
print(torch.mm(data_tensor, data_tensor))

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
tensor([[ 7., 10.],
        [15., 22.]])


In [26]:
torch_arrange = torch.arange(1, 10)
print(torch_arrange)
tesnor, long_tesnor = torch.topk(torch_arrange, 3)
print(tesnor)
print(long_tesnor)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([9, 8, 7])
tensor([8, 7, 6])


In [29]:
zero_tensor = torch.zeros(2,1,2,1,2)
print(zero_tensor)
print(zero_tensor.size())
zero_tensor_squeeze = zero_tensor.squeeze()
print(zero_tensor_squeeze)
print(zero_tensor_squeeze.size())


tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])
torch.Size([2, 1, 2, 1, 2])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
torch.Size([2, 2, 2])


In [2]:
tensor = torch.tensor([1, 2, 3, 4])
print(tensor)
print(torch.unsqueeze(tensor,0))
print(torch.unsqueeze(tensor,1))


tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [8]:
torch.randint(33, size=(1,)).item()

3